title: Rami BABAS
logo: /assets/img/headshot_circle.png
description: Innovative Biotechnologist | AI-Driven | Food Scientist | Biomedical Engineer | Problem-Solver
show_downloads: true
theme: jekyll-theme-minimal
