title: Rami Babas
logo: /assets/img/headshot_circle.png
description: Biotechnology Engineer | AI & Deep Learning | Bioinformatics | Computational Modeling | Problem-Solver
show_downloads: true
theme: jekyll-theme-minimal
